import { Metadata } from "next"

export const MAIN_METADATA: Metadata = {
  title: "mfloww",
  description:
    "Open source money flow visualization application that respects your privacy.",
  applicationName: "mfloww",
  authors: [{ name: "Besim Gürbüz", url: "https://besim.dev" }],
  manifest: "/manifest.json",
  keywords: [
    "money",
    "flow",
    "chart",
    "currency",
    "open source",
    "privacy",
    "security",
    "encryption",
    "budget",
    "expense",
    "income",
    "finance",
    "personal finance",
    "secure finance",
    "own your data",
    "encrypted finance",
    "money flow",
    "money management",
    "money tracker",
    "money tracking",
    "money flow chart",
    "money flow tracker",
    "money flow tracking",
    "money flow management",
    "money flow monitor",
    "money flow visualization",
    "money flow analysis",
    "money flow report",
    "money flow statistics",
    "money flow insights",
    "money flow trends",
    "money flow comparison",
    "money flow planner",
    "money flow budget",
    "money flow expense",
    "money flow income",
    "money flow management system",
    "money flow tracker app",
    "money flow tracking app",
    "money flow management app",
    "money flow monitor app",
    "money flow visualization app",
    "money flow analysis app",
    "money flow report app",
    "money flow statistics app",
    "money flow insights app",
    "money flow trends app",
    "money flow comparison app",
    "money flow planner app",
    "money flow budget app",
    "money flow expense app",
    "money flow income app",
    "money flow management system app",
    "money flow tracker application",
    "money flow tracking application",
    "money flow management application",
    "money flow monitor application",
    "money flow visualization application",
    "money flow analysis application",
    "money flow report application",
    "money flow statistics application",
    "money flow insights application",
    "money flow trends application",
    "money flow comparison application",
    "money flow planner application",
    "money flow budget application",
    "money flow expense application",
    "money flow income application",
    "money flow management system application",
  ],
  creator: "Besim Gürbüz",
  twitter: {
    site: "@mflowwcom",
    creator: "@besimdev",
    title: "mfloww",
    description:
      "Open source money flow visualization application that respects your privacy.",
    card: "summary_large_image",
    images: "/og-image.png",
  },
  icons: [
    {
      rel: "apple-touch-icon",
      url: "/apple-touch-icon.png",
    },
  ],
}
